"""Daily digest: the healthy items that are *on sale* right now.

Built for an unattended (cron/systemd) run — scrapes (or reads cache), keeps
only discounted items scoring well for a training diet, and writes a Markdown
summary plus an echo to stdout (so the service journal captures it).

    lidl-summary                 # scrape live, score >= 6, write today's digest
    lidl-summary --cache         # use the last scrape instead of fetching
    lidl-summary --input fx.json # score an explicit products JSON (testing)
    lidl-summary --min-score 8 --top 20
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

from lidl.scraper import CACHE_FILE, Product, clean_price, scrape
from lidl.scorer import rank_products

BASE = Path(__file__).resolve().parent.parent
OUT_DIR = BASE / "summaries"


def on_sale(p: Product) -> bool:
    """A product is discounted when it carries a struck-through old price."""
    return bool((p.old_price or "").strip())


def _stars(score: int) -> str:
    if score >= 12:
        return "★★★★★"
    if score >= 8:
        return "★★★★☆"
    if score >= 5:
        return "★★★☆☆"
    return "★★☆☆☆"


def load_products(input_path: str | None, use_cache: bool, headless: bool) -> list[Product]:
    if input_path:
        raw = json.loads(Path(input_path).read_text(encoding="utf-8"))
    elif use_cache:
        if not CACHE_FILE.exists():
            sys.exit("no cache found — run a scrape first, or drop --cache")
        raw = json.loads(CACHE_FILE.read_text(encoding="utf-8"))
    else:
        return scrape(use_cache=False, headless=headless)
    fields = Product.__dataclass_fields__
    return [Product(**{k: v for k, v in d.items() if k in fields}) for d in raw]


def build_markdown(items, min_score: int, when: str) -> str:
    lines = [
        f"# 🥗 Lidl healthy on-sale picks — {when}",
        "",
        f"**{len(items)}** discounted item{'s' if len(items) != 1 else ''} "
        f"scoring ≥ {min_score} for a training diet.",
        "",
    ]
    if not items:
        lines.append("_Nothing on sale cleared the bar today._")
    else:
        lines += ["| # | Score | Item | Now | Was | Tags | Category |",
                  "|--:|:--|:--|--:|--:|:--|:--|"]
        for i, sp in enumerate(items, 1):
            p = sp.product
            now = clean_price(p.price)
            was = clean_price(p.old_price)
            tags = " ".join(sp.tags) if sp.tags else ""
            name = p.name.replace("|", "\\|")
            lines.append(
                f"| {i} | {_stars(sp.score)} {sp.score} | {name} | {now} | {was} | "
                f"{tags} | {p.category} |")
    lines += ["", "_Generated by little-lidl-list · prices from lidl.bg_"]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(prog="lidl-summary",
                                 description="Daily digest of healthy on-sale Lidl items")
    ap.add_argument("--min-score", type=int, default=6,
                    help="minimum health score to include (default: 6)")
    ap.add_argument("--top", type=int, default=0, help="cap to top N (0 = all)")
    ap.add_argument("--cache", action="store_true", help="use cached scrape")
    ap.add_argument("--input", help="score products from an explicit JSON file")
    ap.add_argument("--out", default=str(OUT_DIR), help="output directory")
    ap.add_argument("--no-headless", action="store_true", help="show the browser while scraping")
    ap.add_argument("--no-image", action="store_true",
                    help="skip the meal-plan PNG card (Markdown + checklist only)")
    args = ap.parse_args()

    products = load_products(args.input, args.cache, headless=not args.no_headless)
    ranked = rank_products(products, min_score=args.min_score)
    on_sale_items = [sp for sp in ranked if on_sale(sp.product)]
    if args.top > 0:
        on_sale_items = on_sale_items[:args.top]

    when = date.today().isoformat()
    md = build_markdown(on_sale_items, args.min_score, when)

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"lidl-summary-{when}.md"
    out_file.write_text(md, encoding="utf-8")

    print(md)
    print(f"\n[written: {out_file}]", file=sys.stderr)

    # Chain a 3-meal plan + shopping list + phone exports onto the digest, so
    # the daily timer produces them in the same run.
    from lidl.mealplan import build_meal_plan, write_exports
    meals = build_meal_plan(on_sale_items)
    extras = write_exports(meals, when, out_dir, make_image=not args.no_image)
    for label, path in extras.items():
        print(f"[meal-plan {label}: {path}]", file=sys.stderr)


if __name__ == "__main__":
    main()
